language: java
jdk:
  -openjdk8

addons:
  sonarcloud:
    organization: "lomels"
    token: travis encrypt 1c26e48cc9bba2bdc0695100fb768afc81ce2eba

script: 
  - ant build
  - sonar-scanner